name: Node.js CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    default: 'warning'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: 'https://github.com/NicolasLopes7/gh-actions-replace-test-poc'
          path: tests
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Bump tests from template repo
          add: '.'
      - run: npm ci
      - run: npm test
